QOLOE-22 Footer container's gutter value
qld-gov-au/qgds-bootstrap5 pull request #180
Opened 2024-05-31 06:57 UTC by ghazal-salehi

2024-05-31 10:03 UTC, stvp-qld reviewed
.

2024-05-31 10:21 UTC, duttonw approved these changes

2024-06-01 12:13 UTC, stvp-qld requested changes
Can we check/confirm the 40px footer requirement please. The left/right rail of footer should be consistent with header and body content.

2024-06-03 04:26 UTC, ghazal-salehi commented
The last change aligns the footer with qld-content. Example page: https://uat.forgov.qld.gov.au/user
Content page standard paint layout: https://oss-uat.clients.squiz.net/_admin/?screen=contents&assetid=471738

2024-06-06 11:19 UTC, MitchAnderson93 submitted a review, later dismissed
Looks good

2024-06-06 20:42 UTC, duttonw approved these changes

2024-06-10 22:23 UTC, duttonw approved these changes

2024-06-10 22:23 UTC, duttonw commented
Hi @ghazal-salehi ,

I've fixed the merge conflict and rebased your work to remove the noise. Can you please re-review your code changes and merge if its still correct.

Regards,

@duttonw

2024-06-10 22:35 UTC, ghazal-salehi commented
> Hi @ghazal-salehi ,
> 
> I've fixed the merge conflict and rebased your work to remove the noise. Can you please re-review your code changes and merge if its still correct.
> 
> Regards,
> 
> @duttonw

The files changed are as what expected. Merge was still blocked. I did re-request just now.

2024-06-11 00:48 UTC, duttonw submitted a review, later dismissed

2024-06-11 00:51 UTC, duttonw commented on src/components/bs5/footer/footer.scss
> +    --qld-gutter-x: 2.5rem;
this should be changed to (--#{$prefix} per the others

2024-06-11 00:51 UTC, duttonw commented on src/components/common/layout/content.scss
> +        --qld-gutter-x: 2.5rem;
this should be changed to (--#{$prefix} instead of --qld 
so that prefix overrides are happy.

2024-06-11 01:06 UTC, duttonw commented
> > Hi @ghazal-salehi ,
> > I've fixed the merge conflict and rebased your work to remove the noise. Can you please re-review your code changes and merge if its still correct.
> > Regards,
> > @duttonw
> 
> The files changed are as what expected. Merge was still blocked. I did re-request just now.

This was due to a 'request changes' pr review, I've dismissed that review, but there is extra tweaks work that needs to be done to ensure this is not flakey.

2024-06-11 22:29 UTC, ghazal-salehi commented
The merge is blocked. Do you mind taking a look?

2024-06-11 22:39 UTC, duttonw commented
> The merge is blocked. Do you mind taking a look?

Hi @jortronQGov, @stvp-qld, @re-becca,

Please PR review this change and approve.

Regards,

@duttonw

2024-06-11 22:40 UTC, duttonw reviewed
looks good, awaiting Online Experience team to provide approvals.

2024-06-12 04:29 UTC, SenChung approved these changes
Looks good.

2024-06-12 23:12 UTC, elvishu approved these changes
Looks good, Ghazal.

2024-06-12 23:16 UTC, merged