QOLOE-171 Typography QA
qld-gov-au/qgds-bootstrap5 pull request #200
Opened 2024-06-06 05:18 UTC by tedqgov

QA issue: https://ssq-qol.atlassian.net/browse/QOLOE-171

2024-06-06 20:41 UTC, duttonw requested changes
Can another help out in showing a way to not need !important. It should only be used sparingly and this is clean room, so you should be able to rejig the css to accommodate what you want to do. 

Leave this in will cause much pain in the future.

2024-06-06 20:41 UTC, duttonw commented on src/scss/qld-type.scss
> +    --qld-link-visited: var(--qld-link-visited-dark)!important;
is !important really required?
There should be a better way of doing this.

2024-06-06 20:41 UTC, duttonw commented on src/scss/qld-type.scss
> +    line-height: 1.5!important;
ditto (is there a better way instead of getting out the override hammer)

2024-06-06 20:41 UTC, duttonw commented on src/scss/qld-type.scss
> +                color: var(--qld-link-visited-dark)!important;
simliar

2024-06-07 03:27 UTC, re-becca commented
@tedqgov Noticed two minor things for link underline:

- light/alternative - visited:hover should have a text-decoration-color of #551A8B (use associated variable)
- dark/darkalt - default:hover should have a text-decoration-color of #FFFFFF (use associated variable)

2024-06-07 04:03 UTC, tedqgov commented
@re-becca Alright, I made the changes and cleaned up the code more, also added a new colour variable "$qld-link-dark-underline" in the variables file -- let me know if there's anything else you need :)

2024-06-07 04:11 UTC, MitchAnderson93 requested changes

2024-06-07 04:13 UTC, tedqgov commented on src/scss/qld-variables.scss
> +$qld-link-visited: #551A8B;
@MitchAnderson93 Yeah I noticed when fixing up conflicts, I left the colour in hex code for now in qld-type.scss

2024-06-07 04:34 UTC, tedqgov commented
Had to reset my commit due to merge conflicts, will take a while

2024-06-11 01:04 UTC, duttonw commented
Hi @tedqgov ,
Is this included in https://github.com/qld-gov-au/qgds-bootstrap5/pull/214


So this can be closed then?

2024-06-11 01:09 UTC, closed without merging

2024-06-11 01:12 UTC, tedqgov commented
@duttonw Nope not included, will delete this branch -- I cherrypicked commits to the new branch due to git rebase looping bug.