QOLOE-380 move img to be relative to js/css and have it copied into dist/assets folder for reference
qld-gov-au/qgds-bootstrap5 pull request #356
Opened 2024-07-09 01:28 UTC by duttonw

plus minor cleanup

2024-07-09 02:33 UTC, jortronQGov requested changes
Do references to `/assets/img` path need to be updated throughout the repo? e.g. Header svg icons are missing - https://660e3e06af8da379e06be302-ghskoguslb.chromatic.com/?path=/docs/core-header--header

Navbar data.json filenames have misspelling of variant as 'varient'.

2024-07-09 04:01 UTC, duttonw commented
> Do references to `/assets/img` path need to be updated throughout the repo? e.g. Header svg icons are missing - https://660e3e06af8da379e06be302-ghskoguslb.chromatic.com/?path=/docs/core-header--header
> 
> Navbar data.json filenames have misspelling of variant as 'varient'.

It should work, but will need to wait for chromatic to take screenshots. the /assets/img/ is correct in the dist folder.

2024-07-09 05:45 UTC, jortronQGov submitted a review, later dismissed
Thanks @duttonw, looks good now 👍

2024-07-10 01:27 UTC, jortronQGov approved these changes

2024-07-10 01:28 UTC, merged