Qgds qoloe 688 cta
qld-gov-au/qgds-bootstrap5 pull request #524
Opened 2024-11-10 23:58 UTC by SenChung

Fix: CTA button in banner alignment
-> The first CTA button will not have a left margin, this will make it align with the rest of the text

2025-01-15 09:32 UTC, elvishu requested changes
@SenChung, please tidy up the code commit to just the JIRA ticket to make it easier for us to review.

Likely just need this code on .btn class:

```
      &:first-of-type {
        margin-inline-start: 0;
      }
```

Thank you.

2025-01-15 09:36 UTC, elvishu commented
@SenChung,

This PR appears to be very similar to another PR: https://github.com/qld-gov-au/qgds-bootstrap5/pull/527
Please close this one if it is a dupe.

Thank you.

2025-02-12 01:12 UTC, duttonw approved these changes
sass cleanup. 

LGTM

2025-03-11 04:15 UTC, stvp-qld commented
Withdrawn and change included under branch QGDS-125-Banner-Advanced-CTA-with-variants

2025-03-11 04:15 UTC, closed without merging