Qoloe 667 qgdsb5 existing banner component
qld-gov-au/qgds-bootstrap5 pull request #543
Opened 2024-11-19 04:46 UTC by SenChung

Changes need for Storybook to include the Advance Banner Variation

2025-02-12 01:09 UTC, duttonw requested changes
documentation update, unsure what else needs to be updated (have not done chromatic/figma cross review just yet)

2025-02-12 01:09 UTC, duttonw commented on src/components/bs5/banner/banner.stories.js
> +export const AdvanceBanner = {
can you split the story out since vanilla has 3 versions of banner,  (simple, basic, intermediate, advanced)

https://qld-gov-au.github.io/qgds-vanilla/storybook/?path=/docs/components-banner-banner-advanced--overview
https://github.com/qld-gov-au/qgds-vanilla/blob/main/src/components/banner_advanced/stories/bannerAdvanced.stories.js

Banner/Banner (Advanced)

2025-02-12 01:09 UTC, duttonw commented on src/components/bs5/banner/banner.stories.js
> +/**
add figma link to advanced banner
https://www.figma.com/design/qKsxl3ogIlBp7dafgxXuCA/QLD-GOV-DDS?node-id=7287-691763

cross link to https://www.designsystem.qld.gov.au/components/banners#section__advanced-banner

2025-03-12 23:09 UTC, stvp-qld commented
Changes captured by branch QGDS-125-Banner-Advanced-CTA-with-variants, so they can be tested together with other Banner updates.

2025-03-12 23:09 UTC, closed without merging